### ISSUE TITLE
Compilation issues after an upgrade in memmap (from 0.5.2 to 0.6.0)

### ISSUE THREAD

**Issue by mdashti** [frankmcsherry/graph-map#1]
The project cannot be built successfully right now. It fails with the following error:

```
   Compiling graph_map v0.1.0 (https://github.com/frankmcsherry/graph-map.git#952c3266)
error[E0433]: failed to resolve. Could not find `Protection` in `memmap`
  --> /Users/dashti/.cargo/git/checkouts/graph-map-e05b33cd78de9f1d/952c326/src/typed_map.rs:21:52
   |
21 |             map: memmap::Mmap::open(&file, memmap::Protection::Read).unwrap(),
   |                                                    ^^^^^^^^^^ Could not find `Protection` in `memmap`

error[E0599]: no function or associated item named `open` found for type `memmap::Mmap` in the current scope
  --> /Users/dashti/.cargo/git/checkouts/graph-map-e05b33cd78de9f1d/952c326/src/typed_map.rs:21:18
   |
21 |             map: memmap::Mmap::open(&file, memmap::Protection::Read).unwrap(),
   |                  ^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `ptr` found for type `memmap::Mmap` in the current scope
  --> /Users/dashti/.cargo/git/checkouts/graph-map-e05b33cd78de9f1d/952c326/src/typed_map.rs:32:49
   |
32 |         unsafe { slice::from_raw_parts(self.map.ptr() as *const T, self.len) }
   |                                                 ^^^

error: aborting due to 3 previous errors
```
